### ISSUE TITLE
graphviz

### ISSUE THREAD

**Issue by kobuworks** [crossroadsfpga/pigasus#9]
Hi, 
graphviz is available, however following error occurs, does anyone have BKM? 
thanks,
BR/Kobu
===================================================
$ sudo python3 pigasus.py 
Traceback (most recent call last):
  File "pigasus.py", line 19, in <module>
    from fluid.visualizer import *
  File "/home/kobu/kobuworks/pigasus/fluid/visualizer.py", line 1, in <module>
    from graphviz import Graph, Digraph
ModuleNotFoundError: No module named 'graphviz'

**Comment by hsadok** [comment]
Have you tried running the following?
```
sudo python3 -m pip install graphviz
```

**Comment by sidsahay** [comment]
Oh, I see the problem. Turns out we were using an older version of PyGraphviz. In newer versions, PyGraphviz expects `from pygraphviz import AGraph` and has a slightly different API. While I update it, you can comment out 
`from fluid.visualizer import *` on line 19 of `pigasus.py` and 
`pass_manager.add_pass(generate_visualizer_pass(VisualizerType.DEFAULT))` on line 685 of `pigasus.py`
to disable the visualizer. It will still generate designs.
